#Author CptR3dBeard
#Description
# This is a an API that will talk with my python code and perform data analytics models
# on a dataset stored within MongoDB. The goal is to enable a user to get the predictions from 3 different models
# of regression and return them to the screen as a list for the user to do as they wish.

#Imported and Used Libraries
from starlette.responses import FileResponse
from fastapi import FastAPI, UploadFile, File
from fastapi.responses import HTMLResponse, FileResponse
from main import insert_new_dataset,LinearR,Ridge_Regression

app = FastAPI()                             # defining app for FastAPI

@app.get('/', response_class=HTMLResponse)  # This is our landing page that will tell the user
async def read_index():
    return FileResponse('frontend/index.html')

@app.post('/UploadFile/')
def create_upload_file(file: UploadFile = File(...)):
    return insert_new_dataset(file.file)

@app.get('/LinearRegression')               #Get request that returns Linear Regression outcome
def request_for_linear_regression():        #That is generated by our linear regression model
    return LinearR()                     #That we imported from main.py

@app.get('/RidgeRegression')                #Get request that return Ridge Regression outcome
def request_for_linear_regression():        #That is generated by the ridge regression model
    return Ridge_Regression()               # we have imported from main.py
